### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by Anish-Sek** [reactoimpact/CompassCal2#3]
KeyError: 'd'

Traceback (most recent call last):
  File "\week.py", line 34, in <module>
    for session in response.json()['d']:
                   ~~~~~~~~~~~~~~~^^^^^
KeyError: 'd'

**Comment by reactoimpact** [comment]
Hi @Anish-Sek,

This error is because of how the 'ASP.NET_SessionId' resets every week. You can fix it by grabbing the new 'ASP.NET_SessionId' off the compass website.
I believe this only happens if the session id us not used for a long period of time.
